plugins:
  jwt_session_enabled:
    default: true
    client: true
  jwt_session_cookie_name:
    default: discourse_jwt
    client: false
  jwt_session_signing_secret:
    default: ""
    client: false
    secret: true
